### ISSUE TITLE
Release Trigger Strategy

### ISSUE THREAD

**Issue by philnewm** [ynput/ci-tools#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

This ticket describes how we could implement a unified system for creating Releases.
For now, it should produce similar results to the [milestone_release_trigger](https://github.com/ynput/OpenPype/blob/develop/.github/workflows/miletone_release_trigger.yml) in OpenPype.

### Approach
* It should be implemented as GitHub Actions
* We want the system to be abstracted to a point where we can configure and modify it to fit as many cases as possible
* the core system only depends on inputs (those must be given in a specific way but do not depend on, e.g. milestones)

### Naming
* Release : a full release should be used by client
* Pre-release/Nightly-Build: for internal testing - consider as release candidate but is missing QA, ...

### Targets
* Reduce the amount of work a dev has to do to create a release
* Efficiently collect and order all changes between releases
* Ensuring/enforcing a CI-dependent workflow for release creation to increase the product's stability in releases
* Reduce the friction for pre and full-releases

### General Features
* Automatic
  * Merge develop to main after PR is approved
  * Create pre-release
  * Merge main back to develop to stay in sync
* Manual
  * Button from Actions Page, Milestone, Project, ... to create pre-release
  * Label to trigger specific behavior
  * Maintainer can create a full release out of a pre-release using a button

### Steps pre-release
* Merge from develop to main (this ensures that only main can create pre-release)
* Auto naming (version and release name) date/time-stamp for versioning
* Ensure that a pre release is always created and an release is created from a pre-release
* Make sure that artefacts are managed in the way the repo needs it
* Automatic change log (either from milestone, project or PRs since last release)
* Make sure that changelog details can be changed before release to allow for adjustments
* Check for expected outputs

### How would you imagine the implementation of the feature?
* Build a GitHub action that can take parameters for control (this should be fully self-contained and abstract) 
* Create a mock-up action to provide the required changelog data
* Build an example repo that mimics a typical dev workflow and implement the action
* Build an automated example
* Build a manual example

# Further Details
If no input is provided, it should default to just collection the information of any merged PR since the last release and use the last release version tag
This action should be referenced in other repos by just implementing a job which provides the required inputs.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Additional context:

Later on, this can be extended to integrate unit and integration tests.

**Comment by Innders** [comment]
> Merge develop to main after PR is approved
> Create pre-release
> Merge main back to develop to stay in sync

Excuse my ignorance but why does the merging to develop happen last? If the create pre-release fails for any reason, does the next step still happen?

I would have thought it goes. PR -> develop -> main -> pre-release ?

Especially if everyone is relying on develop being the absolute latest changes, I would have thought this needed to be in sync immediately.

**Comment by mkolar** [comment]
That point is correct. After the pre-release main merges back to dev to stay in sync.

However were not merging dev to main after each PR. PRs only go to dev, they accumulate and when we're ready to create a prerelease this whole mechanism kicks in.


The prerelease steps sound correct. I'm assuming that creating a release from that would be simply changing it from pre-release to a release in github, which should then pretty much take that state, regenerate version number (because the prerelease will probably include some extra deliminer) and create the final release from the same commit

**Comment by iLLiCiTiT** [comment]
If we find a bug in pre-release, what would be correct approach to fix it? Make PR to main?

**Comment by philnewm** [comment]
Ah, thanks for clarifying @mkolar 
I wasn't sure if the prerelease should be created automatically or on demand.
But on demand is the way to go then.

**Comment by philnewm** [comment]
@iLLiCiTiT I'm not entirely sure how you guys handle bug fixes.
I would distinguish critical (potential showstoppers for clients) from non-critical (workaround exists or just an inconvenience) bugfixes.

#### Critical Bugfixes
* dedicated bug fix branch which can generate its own prerelease to put out fires quickly if they occur
* they could additionally generate PR's to merge into dev afterwards to evaluate them
* afterwards they can be merged to dev and main

#### Non-Critical Bugfixes
* could be handled just like PR from enhancements
* could be prioritized since they still fix something
* Would be included in next prerelease

Or would a different strategy be preferred here?

**Comment by mkolar** [comment]
We don't categorize them like this. It become too much of micro-management very quickly. If a fix is so critical we can choose to create a separate small release from it via hotfix branch on demand, but it's not often enough to be super systematic

**Comment by philnewm** [comment]
Forgot to close this one - so I'm doing it now
